## All required package installation 

listofpackages<-c("plotly","plyr","gridBase","gridExtra","NLP","imputeTS","wordcloud","devtools","amap","MCMCpack","ggmcmc","zoo","dplyr","plotrix","tabplot","ggplot2","ggmcmc","corrplot","rpart","rattle","grid","psych","wavelets","cluster","tseries","urca","forecast","devtools") 
new.pack<-listofpackages[!(listofpackages %in% installed.packages()[,"Package"])]
if(length(new.pack)) 
  install.packages(new.pack,repos='http://cran.us.r-project.org',dependencies = T)
lapply(listofpackages, require, character.only = TRUE)
library("devtools")
install_github('sinhrks/ggfortify')
library(rpart)
library(forecast)
library(urca)
library(tseries)
library(cluster)
library("rpart")
library("rattle")
library("ggdendro")
library("tabplot")
library(MCMCpack)
library(corrplot)
library(psych)
library("wavelets")
library(dplyr)
library("zoo")
library("ggmcmc")
library("amap")
library("gridBase")
library("NLP")
library("wordcloud")
library("imputeTS")
library("gridExtra")
library("plyr")

